### ISSUE TITLE
[서버-시리얼-아두이노] 기본적인 파라미터 정의 및 협의

### ISSUE THREAD

**Issue by SeunghyeonJeon** [GnuVill-HUFS/2018-Academic-Seminar#17]
서버-시리얼-아두이노의 통신 
<모든 것은 서로간의 협의로 바뀔 수 있습니다. 수정사항은 빠르게 부탁드릴게요!>

1.	def Serial_Connect(car_move)(라즈베리B(시리얼통신)->아두이노)
 이 함수는 라즈베리파이 B가 아두이노쪽으로 동작 전달할 때 사용할게요.
서버 담당분들은 라즈베리파이에서 이 함수 호출할 때 Car_move는 int형으로 작성 부탁드릴게요
 이 함수가 어떤 형식으로 아두이노한테 무슨 값을 전달하면 편하신지 아두이노 담당자께서는 코멘트 부탁드릴게요.
 
2.	Post(아두이노(시리얼통신) -> 라즈베리A)
아두이노에서 모든 동작이 끝나고(에러포함) 그 상태코드들은 post 를 이용하여 라즈베리A로 보내야 합니다. 아두이노 담당분께서는 이 상태코드가 어떤 자료형으로 넘겨주실건지 명시해주세요.

3.	에러처리(시리얼통신중-> 라즈베리A)
시리얼 통신중 생기는 동작 수행실패 코드는 request http통신을 이용하여 라즈베리A로 post 이용하여 넘길 수 있게 작성하겠습니다.

**Comment by roharon** [comment]
@SeunghyeonJeon  @HeoSeungeun  @jenny6585  @saehalee  확인바랍니다

**Comment by saehalee** [comment]
1. 라즈베리B에서는 String형으로 값 전달해 주시면 좋겠어요. 근데 무슨 값으로 줄진 시리얼 통신에서 값을 정해주시면 합니다. 
2. 라즈베리A에 Int형으로 상태코드 반환하겠습니다.

**Comment by saehalee** [comment]
그리고 모터 동작을 8가지로 줄이는 게 어떻까 제안합니다. 
좌앞=1, 앞=2, 우앞=3,
좌측=4,          우측=6,
좌뒤=7, 뒤=8, 우뒤=9
폰 키패드처럼 구현하면 프론트 화면 출력시에도 화살표로 구현하기 편하지 않을까 싶습니다.

**Comment by jenny6585** [comment]
서버 경로는 @app.route('/direction/<direction_code>')  로 설정하겠습니다.

**Comment by jenny6585** [comment]
시리얼에서 예외처리를 위한 반환값은 int형 상태코드로 넘겨주시면 좋겠습니다.
